name: Build

on:
  workflow_call:
    inputs:
      include-functions-build:
        description: 'Whether to build Firebase functions'
        required: false
        type: boolean
        default: false
      fetch-depth:
        description: 'Git fetch depth for semantic release'
        required: false
        type: number
        default: 1
      persist-credentials:
        description: 'Whether to persist git credentials for semantic release'
        required: false
        type: boolean
        default: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
          persist-credentials: ${{ inputs.persist-credentials }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

      - name: Build functions
        if: ${{ inputs.include-functions-build }}
        run: npm run functions:build
        env:
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
