name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write # to push version bump
  issues: write # to comment on issues
  pull-requests: write # to comment on PRs
  checks: write # for unit tests coverage reporting
  id-token: write # for authentication with external services

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    uses: ./.github/workflows/lint-and-format.yml
    with:
      include-functions-lint: true

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    with:
      compare-coverage: true
      coverage-artifact-name: 'coverage-report-pr'

  build:
    needs: [lint-and-format, unit-tests]
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      include-functions-build: true
