
name: Main Branch CI & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # to push version bump
  issues: write # to comment on issues
  pull-requests: write # to comment on PRs
  id-token: write # for authentication with external services

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history for semantic-release to analyze
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Zip coverage report
        if: always()
        run: zip -r coverage.zip coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.zip
          retention-days: 7

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Zip E2E report
        if: always()
        run: zip -r playwright-report.zip playwright-report

      - name: Upload E2E report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-main
          path: playwright-report.zip
          retention-days: 7

      - name: Build project
        run: npm run build

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
