name: Main Branch CI & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # to push version bump
  issues: write # to comment on issues
  pull-requests: write # to comment on PRs
  checks: write # for unit tests coverage reporting
  id-token: write # for authentication with external services

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    uses: ./.github/workflows/lint-and-format.yml

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    with:
      coverage-artifact-name: 'coverage-main'

  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
    needs: unit-tests

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      fetch-depth: 0
      persist-credentials: false
    needs: [lint-and-format, unit-tests, e2e-tests]

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history for semantic-release to analyze
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
