
name: Nightly E2E Tests

on:
  schedule:
    # Runs at 5 AM UTC every day
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    name: Run Nightly E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NEXT_PUBLIC_ENVIRONMENT: test

      - name: Upload test report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-playwright-report
          path: playwright-report/
          retention-days: 7
